### ISSUE TITLE
Support images with premultiplied alpha

### ISSUE THREAD

**Issue by Alloyed** [slages/love-imgui#7]
This is a crosspost of https://github.com/ocornut/imgui/issues/1035

TL;DR: I want to use imgui with premultiplied alpha images, and there's no way (that I can find) to tell love-imgui to do that. 
![2017-02-22-115635_394x230_scrot](https://cloud.githubusercontent.com/assets/137977/23222475/01af757a-f8f6-11e6-921a-ccf3e2b3def9.png)

**Comment by slages** [comment]
I made a change to automatically apply the premultiplied alpha blend mode when imgui.Image or imgui.ImageButton is used to draw a Canvas, it should fix your issue!

I didn't made a new release, so you'll need to build a new version from source.

**Comment by Alloyed** [comment]
Yep, it works! This is maybe less flexible than I imagined (I couldn't have a normal Image use premultiplied alpha for example) but I wasn't planning on doing that sort of thing anyways.
